baseURL = "https://<your-username>.github.io/retroblog/"
languageCode = "en-us"
title = "Retro Cart Detective"
theme = "re-terminal"
enableGitInfo = true

[pagination]
  pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"        # choose: orange, blue, red, green, pink, paper
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = true

  [params.banner]
    dismissible = false
    text = "Welcome to Retro Cart Detective — learn how to spot fakes, preserve classics!"
    url = "/about"

[languages]
  [languages.en]
    languageName = "English"
    title = "Retro Cart Detective"
    subtitle = "Spot the Real, Play the Retro"
    owner = "Jenny"
    keywords = ["retro", "gaming", "fake", "collecting", "guides"]
    copyright = "© 2025 Jenny"
    menuMore = "More"
    readMore = "Read more"
    readOtherPosts = "Other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Retro Cart Detective"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"

    [[languages.en.menu.main]]
      identifier = "guides"
      name = "Guides"
      url = "/tags/fake-check/"

    [[languages.en.menu.main]]
      identifier = "systems"
      name = "Systems"
      url = "/tags/nes/"
