baseURL = "https://jennybuni.github.io/retrobun/"
languageCode = "en-us"
title = "Retrobun Collection"
theme = "re-terminal"
enableGitInfo = false

[pagination]
  pagerSize = 5


[params]
  contentTypeName = "posts"
  themeColor = "pink"        # choose: orange, blue, red, green, pink, paper
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = true
  ReadMore = "Read more"

  [params.banner]
    dismissible = false
    url = "/about"

[languages]
  [languages.en]
    languageName = "English"
    title = "Retrobun collection"
    subtitle = "Search and spot the Real, Play the Retro"
    owner = "Jenny"
    keywords = ["retro", "gaming", "fake", "collecting", "guides"]
    copyright = "© 2025 Jenny"
  menuMore = "More"
  readOtherPosts = "Other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Retrobun Collection"
      logoHomeLink = "/"
      logoImage = "images/logo.png"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"

    [[languages.en.menu.main]]
      identifier = "guides"
      name = "Guides"
      url = "/tags/fake-check/"

    [[languages.en.menu.main]]
      identifier = "systems"
      name = "Systems"
      url = "/tags/systems/"
